using Cysharp.Threading.Tasks;
using PressureExpress.Network;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Main menu, bound to the hand-made MainMenuCanva prefab.
///
/// The first six fields keep the exact names and types they had before, so the references already
/// wired in Assets/Prefab/UI/MainMenu/MainMenuCanva.prefab stay connected. Everything below the
/// "Optional" header is new and can be left empty.
///
/// None of the buttons in that prefab have inspector OnClick entries, so every listener is added
/// here. Managers now live in the Bootstrap scene and cannot hold scene references, so this reaches
/// for SessionService.Instance rather than being wired to it.
/// </summary>
public class MainUI : MonoBehaviour
{
    [SerializeField] private Button joinButton, hostButton, settingButton, discordButton, tutorialButton;
    [SerializeField] private TMP_InputField hostCode, joinCode;
    [SerializeField] private string tutorialSceneName = "Tutorial";

    [Header("Optional — leave empty if you don't have them")]
    [Tooltip("Shows 'Searching...', 'Steam is not running', and every join failure reason.")]
    [SerializeField] private TextMeshProUGUI statusText;

    [Tooltip("Shown only in the Editor's local mode so a loopback session is never mistaken for Steam.")]
    [SerializeField] private GameObject localModeBanner;

    [Tooltip("Panel toggled by the settings button. Usually the object holding SettingsMenu.")]
    [SerializeField] private GameObject settingsPanel;

    [SerializeField] private string discordUrl = "";

    [Header("Behaviour")]
    [Tooltip("Room codes are generated by the host now, so the host code box has nothing to type " +
             "into. Leave this on to hide it, or turn it off and it will display the code instead.")]
    [SerializeField] private bool hideHostCodeField = true;

    private SessionService _session;
    private bool _busy;

    private void OnEnable()
    {
        CursorVisibilityController.OpenUI(this);
    }

    private void Start()
    {
        _session = SessionService.Instance;

        if (settingsPanel != null) settingsPanel.SetActive(false);
        if (localModeBanner != null) localModeBanner.SetActive(false);
        if (hostCode != null && hideHostCodeField) hostCode.gameObject.SetActive(false);

        if (hostButton != null) hostButton.onClick.AddListener(OnHostClicked);
        if (joinButton != null) joinButton.onClick.AddListener(OnJoinClicked);
        if (tutorialButton != null) tutorialButton.onClick.AddListener(OnTutorialClicked);
        if (settingButton != null) settingButton.onClick.AddListener(OnSettingsClicked);
        if (discordButton != null) discordButton.onClick.AddListener(OnDiscordClicked);

        if (joinCode != null)
        {
            joinCode.characterLimit = RoomCode.Length;
            joinCode.onValueChanged.AddListener(OnCodeTyped);
        }

        if (_session == null)
        {
            SetInteractable(false);
            SetStatus("Network services missing. Enter play mode from the Bootstrap scene.");
            return;
        }

        _session.StateChanged += OnSessionStateChanged;
        _session.StatusChanged += SetStatus;

        ApplyAvailability();
    }

    private void OnDestroy()
    {
        CursorVisibilityController.CloseUI(this);

        if (hostButton != null) hostButton.onClick.RemoveListener(OnHostClicked);
        if (joinButton != null) joinButton.onClick.RemoveListener(OnJoinClicked);
        if (tutorialButton != null) tutorialButton.onClick.RemoveListener(OnTutorialClicked);
        if (settingButton != null) settingButton.onClick.RemoveListener(OnSettingsClicked);
        if (discordButton != null) discordButton.onClick.RemoveListener(OnDiscordClicked);
        if (joinCode != null) joinCode.onValueChanged.RemoveListener(OnCodeTyped);

        if (_session == null) return;

        _session.StateChanged -= OnSessionStateChanged;
        _session.StatusChanged -= SetStatus;
    }

    private void OnDisable()
    {
        CursorVisibilityController.CloseUI(this);
    }

    /// <summary>
    /// In a build with Steam unavailable we disable multiplayer and say so, rather than quietly
    /// starting a loopback host that nobody in the world could join.
    /// </summary>
    private void ApplyAvailability()
    {
        if (localModeBanner != null)
        {
            localModeBanner.SetActive(_session.Mode == NetworkMode.LocalLoopback);
        }

        SteamService steam = SteamService.Instance;
        if (_session.Mode == NetworkMode.Steam && (steam == null || !steam.IsReady))
        {
            SetInteractable(false);
            SetStatus("Steam is not running. Please launch the game through Steam.");
            return;
        }

        SetInteractable(true);
        SetStatus(_session.Mode == NetworkMode.LocalLoopback
            ? "Local mode — UnityTransport on 127.0.0.1."
            : string.Empty);
    }

    #region Buttons

    /// <summary>
    /// Keeps the box showing exactly what will be sent. Reads TMP_InputField.text, never the child
    /// TextMeshProUGUI, whose buffer carries a trailing zero width space.
    /// </summary>
    private void OnCodeTyped(string raw)
    {
        string cleaned = RoomCode.Normalize(raw);
        if (cleaned.Length > RoomCode.Length) cleaned = cleaned.Substring(0, RoomCode.Length);

        if (cleaned != raw)
        {
            joinCode.SetTextWithoutNotify(cleaned);
        }
    }

    private void OnHostClicked()
    {
        if (_busy || _session == null) return;
        HostAsync().Forget();
    }

    private async UniTaskVoid HostAsync()
    {
        BeginBusy("Creating room...");
        SessionResult result = await _session.HostAsync();
        EndBusy(result);
        // On success the session loads the game scene, so this menu is going away.
    }

    private void OnJoinClicked()
    {
        if (_busy || _session == null) return;
        JoinAsync().Forget();
    }

    private async UniTaskVoid JoinAsync()
    {
        string typed = joinCode != null ? joinCode.text : string.Empty;

        BeginBusy("Searching for room...");
        SessionResult result = await _session.JoinByCodeAsync(typed);
        EndBusy(result);
    }

    private void OnTutorialClicked()
    {
        if (_busy) return;
        StartTutorialAsync().Forget();
    }

    private async UniTaskVoid StartTutorialAsync()
    {
        BeginBusy("Loading Tutorial...");
        try
        {
            if (_session != null && _session.State != SessionState.Idle)
            {
                await _session.LeaveSessionAsync(returnToMenu: false);
            }
            await UnityEngine.SceneManagement.SceneManager.LoadSceneAsync(tutorialSceneName, UnityEngine.SceneManagement.LoadSceneMode.Single).ToUniTask();
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Failed to load tutorial: {e.Message}");
            EndBusy(default);
        }
    }

    private void OnSettingsClicked()
    {
        if (settingsPanel == null) return;
        settingsPanel.SetActive(!settingsPanel.activeSelf);
    }

    private void OnDiscordClicked()
    {
        if (string.IsNullOrEmpty(discordUrl)) return;
        Application.OpenURL(discordUrl);
    }

    #endregion

    #region State

    private void BeginBusy(string message)
    {
        _busy = true;
        SetInteractable(false);
        SetStatus(message);
    }

    private void EndBusy(SessionResult result)
    {
        _busy = false;
        SetStatus(result.ToMessage());

        if (result != SessionResult.Success)
        {
            ApplyAvailability();
        }
    }

    private void OnSessionStateChanged(SessionState state)
    {
        switch (state)
        {
            case SessionState.Hosting:
                SetStatus("Creating room...");
                break;
            case SessionState.Searching:
                SetStatus("Searching for room...");
                break;
            case SessionState.Connecting:
                SetStatus("Connecting to host...");
                break;
            case SessionState.Idle:
                if (!_busy) ApplyAvailability();
                break;
        }
    }

    private void SetInteractable(bool value)
    {
        if (hostButton != null) hostButton.interactable = value;
        if (joinButton != null) joinButton.interactable = value;
        if (joinCode != null) joinCode.interactable = value;
    }

    private void SetStatus(string message)
    {
        if (statusText == null)
        {
            if (!string.IsNullOrEmpty(message)) Debug.Log($"[MainUI] {message}");
            return;
        }

        statusText.text = message;
    }

    #endregion
}
